services:
  - type: web
    name: ml-emotion-service
    runtime: docker
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
    healthCheckPath: /health